### ISSUE TITLE
The file name is incorrectly encoded after the file is decompressed

### ISSUE THREAD

**Issue by lopo12123** [MCOfficer/zip-extract#14]
My code is as follows, when I unzip my zip file, the Chinese file name inside it is wrongly encoded

``` rust
use std::io::Cursor;
use std::path::{Path, PathBuf};

pub fn extract_zip(zip_buffer: Vec<u8>, dest: &Path) -> Result<(), String> {
    match zip_extract::extract(
        Cursor::new(zip_buffer),
        dest,
        false,
    ) {
        Ok(_) => Ok(()),
        Err(err) => Err(format!("{}", err))
    }
}
```

below is what the code unzips and how it should actually look like
![image](https://github.com/MCOfficer/zip-extract/assets/59609929/29455c1e-1a19-48f0-8552-0a6cc43756d1)
![image](https://github.com/MCOfficer/zip-extract/assets/59609929/9171a524-247a-49de-a6c7-2e36404b77e3)

**Comment by MCOfficer** [comment]
Given that this crate just uses the names as provided by zip-rs, i'm tempted to blame it on upstream. But then again, this is using zip-rs 0.6.4, which is very outdated. Will require further testing, not sure when i'll get to it.

**Comment by RecordingTheSmile** [comment]
Actually, if you clone this repo and change `zip` version to 2.1.3, you can solve this problem **without any modification to code**.

This problem should be related to https://github.com/zip-rs/zip2/issues/159

**Comment by MCOfficer** [comment]
thanks for finding that, i've been meaning to update to zip2 eventually.

**Comment by MCOfficer** [comment]
Big thanks to @DaniPopes for updating zip-extract to v0.2, which uses zip2!
